package com.github.edge.roman.spear.commons

object SpearCommons {
  val InvalidParams = "provided source and destination details are not supported by spear!!"
  val FileUploadSuccess = "File upload successful"
  val CustomSchema = "customSchema"
  val Path = "path"
  val SuccessStatus = "success"
  val FailedStatus = "failed"
  val Default = "Default-spear-connector"
  val Relational = "relational"
  val File = "file"
  val FileSystem = "FS"
  val Stream = "stream"
  val SalesforceFormat = "com.springml.spark.salesforce"
  val FTP = "ftp"
  val AWS = "aws"
  val SMB = "smb"
  val GCS = "gcs"
  val ADLS = "adls"
  val HDFS = "hdfs"
  val LOCAL = "local"
  val Username = "username"
  val Password = "password"
  val ShowNumRows = 10
  val NoSql = "nosql"
  val Parquet = "parquet"
  val Avro = "avro"
  val Jdbc ="jdbc"
  val Mongo="mongo"
  val Cassandra="cassandra"
  val Nosql="nosql"
  val PartitionCols="partition_columns"
  val BucketCols="bucket_columns"
  val Star="*"
  val Graph="graph"
  val NumBuckets="num_buckets"
  val AppName="spark.app.name"
  val DefaultFSPath=""
  val EmptyTable=""
}
